services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_DB: demo_app_dev
      POSTGRES_USER: demo_app_user
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
