spring:
  profile:
    default: dev
  application:
    name: "demo"
  myapp:
    privateKeyPath: "files/private_key_encrypted_dev.pem"
    publicKeyPath: "files/public_key_dev.pem"
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
  #    hikari:
  #      minimum-idle: 10
  #      maximum-pool-size: 10
  #      connection-timeout: 20000
  #      idle-timeout: 300000
  #      max-lifetime: 1200000
  devtools:
    restart:
      enabled: true
    remote:
      secret: foobar
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: INFO
    dev.rockyj: DEBUG
    org.springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always